-- Products named on a manufacturer brochure or product page.
-- A figure is stored only when the source printed it and, for Corobrik sheets, it survived a density check.
-- Prices, stock and photographs are still not published.

alter table brand_skus add column if not exists parent_sku text;
alter table brand_skus add column if not exists spec_status text not null default 'family_only';
alter table brand_skus add column if not exists mass_kg numeric;
alter table brand_skus add column if not exists units_per_m2 numeric;
alter table brand_skus add column if not exists units_per_pallet integer;
alter table brand_skus add column if not exists factory text;
alter table brand_skus add column if not exists source_url text;
alter table brand_skus add column if not exists manufacturer_code text;
create index if not exists brand_skus_parent_idx on brand_skus (parent_sku);

insert into brand_skus (
  sku, brand, brand_slug, family, name, official_url, dimensions, colour_finish, standard_ref, brochure_ref,
  availability_status, delivery_class, image_rights_status, publication_status, source_status, notes,
  parent_sku, spec_status, mass_kg, units_per_m2, units_per_pallet, factory, source_url, manufacturer_code
) values
('BP-CB-1001', 'Corobrik', 'corobrik', 'Clay face bricks', 'Titanium Satin', 'https://www.corobrik.co.za/clay-face-brick-range', '222 x 106 x 73mm', 'Titanium Satin', 'SANS 227:2007', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure', '', 'BP-CB-0001', 'brochure', 2.3, 51, 480, 'Midrand, Gauteng', 'https://www.corobrik.co.za/clay-face-brick-range', 'FBX'),
('BP-CB-1002', 'Corobrik', 'corobrik', 'Clay paving', 'Onyx Piazza', 'https://www.corobrik.co.za/clay-brick-pavers', null, 'Onyx', null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure_name_only', 'Named on a Corobrik paving sheet. The text read size 220 x 52 x 50mm, mass 7.2kg; those figures are not physically consistent, so they are not published.', 'BP-CB-0004', 'brochure_name_only', null, null, null, null, 'https://www.corobrik.co.za/clay-brick-pavers', null),
('BP-CB-1003', 'Corobrik', 'corobrik', 'Clay paving', 'Cederberg Doppio', 'https://www.corobrik.co.za/clay-brick-pavers', '220 x 220 x 50mm', 'Cederberg', null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure', '', 'BP-CB-0004', 'brochure', 5, 20, 250, 'Springs, Gauteng', 'https://www.corobrik.co.za/clay-brick-pavers', null),
('BP-CB-1004', 'Corobrik', 'corobrik', 'Clay paving', 'Onyx Modular', 'https://www.corobrik.co.za/clay-brick-pavers', null, 'Onyx', null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure_name_only', 'Named on a Corobrik paving sheet. The text read size 220 x 708.5 x 50mm, mass 2.6kg; those figures are not physically consistent, so they are not published.', 'BP-CB-0004', 'brochure_name_only', null, null, null, null, 'https://www.corobrik.co.za/clay-brick-pavers', null),
('BP-CB-1005', 'Corobrik', 'corobrik', 'Clay face bricks', 'Silvergrey Travertine', 'https://www.corobrik.co.za/clay-face-brick-range', '222 x 106 x 73mm', 'Silvergrey Travertine', 'SANS 227:2007', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure', '', 'BP-CB-0001', 'brochure', 2.3, 51, 480, 'Midrand, Gauteng', 'https://www.corobrik.co.za/clay-face-brick-range', 'FBX'),
('BP-CB-1006', 'Corobrik', 'corobrik', 'Clay face bricks', 'Agate Satin', 'https://www.corobrik.co.za/clay-face-brick-range', '222 x 106 x 73mm', 'Agate Satin', 'SANS 227:2007', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure', '', 'BP-CB-0001', 'brochure', 2.3, 51, 480, 'Midrand, Gauteng', 'https://www.corobrik.co.za/clay-face-brick-range', 'FBX'),
('BP-CB-1007', 'Corobrik', 'corobrik', 'Clay paving', 'Graphite Modular 65mm Thick', 'https://www.corobrik.co.za/clay-brick-pavers', '220 x 98.5 x 65mm', 'Graphite', null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure', 'Width is printed as 98.5 mm in the brochure text. Confirm against the PDF before quoting.', 'BP-CB-0004', 'brochure', 2.8, 48, 500, 'Springs, Gauteng', 'https://www.corobrik.co.za/clay-brick-pavers', null),
('BP-CB-1008', 'Corobrik', 'corobrik', 'Clay paving', 'Nutmeg Modular 65mm Thick', 'https://www.corobrik.co.za/clay-brick-pavers', '200 x 98.5 x 65mm', 'Nutmeg', null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure', 'Width is printed as 98.5 mm in the brochure text. Confirm against the PDF before quoting. Length is printed as 200 mm. Modular pavers are often 220 mm. Confirm before quoting.', 'BP-CB-0004', 'brochure', 2.8, 48, 500, 'Springs, Gauteng', 'https://www.corobrik.co.za/clay-brick-pavers', null),
('BP-CB-1009', 'Corobrik', 'corobrik', 'Clay face bricks', 'Titanium Travertine', 'https://www.corobrik.co.za/clay-face-brick-range', '222 x 106 x 73mm', 'Titanium Travertine', 'SANS 227:2007', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure', '', 'BP-CB-0001', 'brochure', 2.3, 51, 480, 'Midrand, Gauteng', 'https://www.corobrik.co.za/clay-face-brick-range', 'FBX'),
('BP-CB-1010', 'Corobrik', 'corobrik', 'Clay paving', 'Nutmeg Modular', 'https://www.corobrik.co.za/clay-brick-pavers', null, 'Nutmeg', null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure_name_only', 'Named on a Corobrik paving sheet. The text read size 220 x 708.5 x 50mm, mass 2.6kg; those figures are not physically consistent, so they are not published.', 'BP-CB-0004', 'brochure_name_only', null, null, null, null, 'https://www.corobrik.co.za/clay-brick-pavers', null),
('BP-CB-1011', 'Corobrik', 'corobrik', 'Clay paving', 'Burgundy Doppio', 'https://www.corobrik.co.za/clay-brick-pavers', '220 x 220 x 50mm', 'Burgundy', null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure', '', 'BP-CB-0004', 'brochure', 5, 20, 250, 'Springs, Gauteng', 'https://www.corobrik.co.za/clay-brick-pavers', null),
('BP-CB-1012', 'Corobrik', 'corobrik', 'Clay paving', 'Ironstone Modular', 'https://www.corobrik.co.za/clay-brick-pavers', null, 'Ironstone', null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure_name_only', 'Named on a Corobrik paving sheet. The text read size 220 x 708.5 x 50mm, mass 2.6kg; those figures are not physically consistent, so they are not published.', 'BP-CB-0004', 'brochure_name_only', null, null, null, null, 'https://www.corobrik.co.za/clay-brick-pavers', null),
('BP-CB-1013', 'Corobrik', 'corobrik', 'Clay face bricks', 'Wild Wheat Travertine', 'https://www.corobrik.co.za/clay-face-brick-range', '222 x 106 x 73mm', 'Wild Wheat Travertine', 'SANS 227:2007', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure', '', 'BP-CB-0001', 'brochure', 2.4, 51, 464, null, 'https://www.corobrik.co.za/clay-face-brick-range', 'FBS'),
('BP-CB-1014', 'Corobrik', 'corobrik', 'Clay paving', 'Nutmeg Piazza', 'https://www.corobrik.co.za/clay-brick-pavers', null, 'Nutmeg', null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure_name_only', 'Named on a Corobrik paving sheet. The text read size 220 x 52 x 50mm, mass 7.2kg; those figures are not physically consistent, so they are not published.', 'BP-CB-0004', 'brochure_name_only', null, null, null, null, 'https://www.corobrik.co.za/clay-brick-pavers', null),
('BP-CB-1015', 'Corobrik', 'corobrik', 'Clay face bricks', 'Serengeti Satin', 'https://www.corobrik.co.za/clay-face-brick-range', '222 x 106 x 73mm', 'Serengeti Satin', 'SANS 227:2007', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure', '', 'BP-CB-0001', 'brochure', 2.3, 51, 464, null, 'https://www.corobrik.co.za/clay-face-brick-range', 'FBS'),
('BP-CB-1016', 'Corobrik', 'corobrik', 'Clay face bricks', 'Terracotta Satin', 'https://www.corobrik.co.za/clay-face-brick-range', '222 x 106 x 73mm', 'Terracotta Satin', 'SANS 227:2007', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure', '', 'BP-CB-0001', 'brochure', 2.6, 51, 480, null, 'https://www.corobrik.co.za/clay-face-brick-range', 'FBS'),
('BP-CB-1017', 'Corobrik', 'corobrik', 'Clay paving', 'Nutmeg Doppio', 'https://www.corobrik.co.za/clay-brick-pavers', '220 x 220 x 50mm', 'Nutmeg', null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure', '', 'BP-CB-0004', 'brochure', 5, 20, 250, 'Springs, Gauteng', 'https://www.corobrik.co.za/clay-brick-pavers', null),
('BP-CB-1018', 'Corobrik', 'corobrik', 'Clay paving', 'Champagne Doppio', 'https://www.corobrik.co.za/clay-brick-pavers', '220 x 220 x 50mm', 'Champagne', null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'brochure', '', 'BP-CB-0004', 'brochure', 5, 20, 250, 'Springs, Gauteng', 'https://www.corobrik.co.za/clay-brick-pavers', null),
('BP-BS-1001', 'Bosun', 'bosun', 'Paving', 'Urban Small / Standard', 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', '200 x 100 x 60 mm', null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Plan size and thickness as published on Bosun’s browse-by-size page. Colour is not fixed on that page.', 'BP-BS-0001', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', null),
('BP-BS-1002', 'Bosun', 'bosun', 'Paving', 'Urban Medium', 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', '200 x 150 x 60 mm', null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Plan size and thickness as published on Bosun’s browse-by-size page. Colour is not fixed on that page.', 'BP-BS-0001', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', null),
('BP-BS-1003', 'Bosun', 'bosun', 'Paving', 'Smooth Ethnic', 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', '200 x 150 x 55 mm', null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Plan size and thickness as published on Bosun’s browse-by-size page. Colour is not fixed on that page.', 'BP-BS-0001', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', null),
('BP-BS-1004', 'Bosun', 'bosun', 'Paving', 'Venetian', 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', '255 x 55 x 60 mm', null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Plan size and thickness as published on Bosun’s browse-by-size page. Colour is not fixed on that page.', 'BP-BS-0001', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', null),
('BP-BS-1005', 'Bosun', 'bosun', 'Paving', 'Bosun Cobble', 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', '150 x 150 mm, 55 or 60 mm thick', null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Plan size and thickness as published on Bosun’s browse-by-size page. Colour is not fixed on that page.', 'BP-BS-0001', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', null),
('BP-BS-1006', 'Bosun', 'bosun', 'Paving', 'Urban Slimline', 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', '200 x 400 x 60 mm', null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Plan size and thickness as published on Bosun’s browse-by-size page. Colour is not fixed on that page.', 'BP-BS-0001', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', null),
('BP-BS-1007', 'Bosun', 'bosun', 'Paving', 'Urban Large', 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', '300 x 400 x 60 mm', null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Plan size and thickness as published on Bosun’s browse-by-size page. Colour is not fixed on that page.', 'BP-BS-0001', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', null),
('BP-BS-1008', 'Bosun', 'bosun', 'Paving', 'Linneo Small', 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', '300 x 120 x 80 mm', null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Plan size and thickness as published on Bosun’s browse-by-size page. Colour is not fixed on that page.', 'BP-BS-0001', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', null),
('BP-BS-1009', 'Bosun', 'bosun', 'Paving', 'Linneo Large', 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', '600 x 240 x 80 mm', null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Plan size and thickness as published on Bosun’s browse-by-size page. Colour is not fixed on that page.', 'BP-BS-0001', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', null),
('BP-BS-1010', 'Bosun', 'bosun', 'Paving', 'Urban XXL', 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', '600 x 900 x 80 mm', null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Plan size and thickness as published on Bosun’s browse-by-size page. Colour is not fixed on that page.', 'BP-BS-0001', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/paving/designer-paving/browse-by-size/', null),
('BP-BS-1011', 'Bosun', 'bosun', 'Paving', '60/80 mm Interlocking Paver', 'https://www.bosun.co.za/products/paver-tips-and-colour-advice/', '60 or 80 mm thick; plan size not stated', 'Organic: Kalahari, Basalt. Colourfast: Ebony, Ivory, Ash. Standard colours also offered.', null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colours named on Bosun’s paver tips page. Plan size was not stated, so it is not invented.', 'BP-BS-0001', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/paver-tips-and-colour-advice/', null),
('BP-BS-1012', 'Bosun', 'bosun', 'Kerbs', 'Figure 3 kerb', 'https://www.bosun.co.za/products/kerbs/', null, null, 'Stated SANS compliant; the standard number is not on the category page', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Named on the Bosun kerbs page. No section size was published there.', 'BP-BS-0002', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/kerbs/', null),
('BP-BS-1013', 'Bosun', 'bosun', 'Kerbs', 'Figure 4 light duty barrier kerb', 'https://www.bosun.co.za/products/kerbs/', null, null, 'Stated SANS compliant; the standard number is not on the category page', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Named on the Bosun kerbs page. No section size was published there.', 'BP-BS-0002', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/kerbs/', null),
('BP-BS-1014', 'Bosun', 'bosun', 'Kerbs', 'Figure 7 semi-mountable kerb', 'https://www.bosun.co.za/products/kerbs/', null, null, 'Stated SANS compliant; the standard number is not on the category page', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Named on the Bosun kerbs page. No section size was published there.', 'BP-BS-0002', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/kerbs/', null),
('BP-BS-1015', 'Bosun', 'bosun', 'Kerbs', 'Figure 8B medium duty mountable kerb', 'https://www.bosun.co.za/products/kerbs/', null, null, 'Stated SANS compliant; the standard number is not on the category page', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Named on the Bosun kerbs page. No section size was published there.', 'BP-BS-0002', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/kerbs/', null),
('BP-BS-1016', 'Bosun', 'bosun', 'Kerbs', 'Figure 8C heavy duty mountable kerb', 'https://www.bosun.co.za/products/kerbs/', null, null, 'Stated SANS compliant; the standard number is not on the category page', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Named on the Bosun kerbs page. No section size was published there.', 'BP-BS-0002', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/kerbs/', null),
('BP-BS-1017', 'Bosun', 'bosun', 'Kerbs', 'Channel kerb', 'https://www.bosun.co.za/products/kerbs/', null, null, 'Stated SANS compliant; the standard number is not on the category page', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Named on the Bosun kerbs page. No section size was published there.', 'BP-BS-0002', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/kerbs/', null),
('BP-BS-1018', 'Bosun', 'bosun', 'Kerbs', 'Delineator kerb', 'https://www.bosun.co.za/products/kerbs/', null, null, 'Stated SANS compliant; the standard number is not on the category page', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Named on the Bosun kerbs page. No section size was published there.', 'BP-BS-0002', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/kerbs/', null),
('BP-TC-1001', 'Technicrete', 'technicrete', 'Erosion control', 'Armorflex 140', 'https://www.technicrete.co.za/products/armorflex-140/', '340 x 400 x 95 mm', 'Grey, Tan, Slate, Plum, Autumn, Terracotta. Special colours made to order.', null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Open area 18%. Unit weight 140 kg/m2. From the Armorflex 140 product page.', 'BP-TC-0004', 'manufacturer_page', 17.5, 8, null, null, 'https://www.technicrete.co.za/products/armorflex-140/', null),
('BP-TC-1002', 'Technicrete', 'technicrete', 'Erosion control', 'Armorflex 165', 'https://www.technicrete.co.za/product-category/building-infrastructure', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Named on the Technicrete building and infrastructure category. The specification table was not retrieved. No size is published here.', 'BP-TC-0004', 'manufacturer_page', null, null, null, null, 'https://www.technicrete.co.za/product-category/building-infrastructure', null),
('BP-TC-1003', 'Technicrete', 'technicrete', 'Erosion control', 'Armorflex 180', 'https://www.technicrete.co.za/product-category/building-infrastructure', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Named on the Technicrete building and infrastructure category. The specification table was not retrieved. No size is published here.', 'BP-TC-0004', 'manufacturer_page', null, null, null, null, 'https://www.technicrete.co.za/product-category/building-infrastructure', null),
('BP-TC-1004', 'Technicrete', 'technicrete', 'Erosion control', 'Armorflex 205', 'https://www.technicrete.co.za/product-category/building-infrastructure', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Named on the Technicrete building and infrastructure category. The specification table was not retrieved. No size is published here.', 'BP-TC-0004', 'manufacturer_page', null, null, null, null, 'https://www.technicrete.co.za/product-category/building-infrastructure', null),
('BP-TC-1005', 'Technicrete', 'technicrete', 'Erosion control', 'Armorflex 405', 'https://www.technicrete.co.za/product-category/building-infrastructure', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Named on the Technicrete building and infrastructure category. The specification table was not retrieved. No size is published here.', 'BP-TC-0004', 'manufacturer_page', null, null, null, null, 'https://www.technicrete.co.za/product-category/building-infrastructure', null),
('BP-TC-1006', 'Technicrete', 'technicrete', 'Erosion control', 'Armorflex HLP', 'https://www.technicrete.co.za/product-category/building-infrastructure', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Named on the Technicrete building and infrastructure category. The specification table was not retrieved. No size is published here.', 'BP-TC-0004', 'manufacturer_page', null, null, null, null, 'https://www.technicrete.co.za/product-category/building-infrastructure', null),
('BP-TC-1007', 'Technicrete', 'technicrete', 'Paving', 'Bondbrick', 'https://www.technicrete.co.za/product-category/building-infrastructure', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Named on the Technicrete building and infrastructure category. The specification table was not retrieved. No size is published here.', 'BP-TC-0001', 'manufacturer_page', null, null, null, null, 'https://www.technicrete.co.za/product-category/building-infrastructure', null),
('BP-TC-1008', 'Technicrete', 'technicrete', 'Paving', 'Concobble', 'https://www.technicrete.co.za/product-category/building-infrastructure', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Named on the Technicrete building and infrastructure category. The specification table was not retrieved. No size is published here.', 'BP-TC-0001', 'manufacturer_page', null, null, null, null, 'https://www.technicrete.co.za/product-category/building-infrastructure', null),
('BP-TC-1009', 'Technicrete', 'technicrete', 'Paving', 'Conleaf', 'https://www.technicrete.co.za/product-category/building-infrastructure', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Named on the Technicrete building and infrastructure category. The specification table was not retrieved. No size is published here.', 'BP-TC-0001', 'manufacturer_page', null, null, null, null, 'https://www.technicrete.co.za/product-category/building-infrastructure', null),
('BP-TC-1010', 'Technicrete', 'technicrete', 'Paving', 'Satin Pave', 'https://www.technicrete.co.za/products/satin-pave/', '205 x 105 mm, in 55, 60 or 80 mm', 'Autumn, Terracotta, Grey, Plum, Slate, Tan', null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Thicknesses and plan size from the Satin Pave product page. 41 blocks per m2.', 'BP-TC-0001', 'manufacturer_page', null, 41, null, null, 'https://www.technicrete.co.za/products/satin-pave/', null),
('BP-TC-1011', 'Technicrete', 'technicrete', 'Erosion control', 'Deckwerk', 'https://www.technicrete.co.za/products/deckwerk/', '240 x 240 x 100 mm', 'Standard grey. Coloured on request.', null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'From the Deckwerk product page.', 'BP-TC-0004', 'manufacturer_page', null, 17, null, null, 'https://www.technicrete.co.za/products/deckwerk/', null),
('BP-IF-1001', 'Infraset', 'infraset', 'Roof tiles', 'Horizon Brown Standard', 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 5 kg. 10.42 tiles/m2. Minimum pitch 17 degrees.', 'Brown Standard', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Horizon product page.', 'BP-IF-0002', 'manufacturer_page', 5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', 'HZ BR STD'),
('BP-IF-1002', 'Infraset', 'infraset', 'Roof tiles', 'Horizon Amber Standard', 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 5 kg. 10.42 tiles/m2. Minimum pitch 17 degrees.', 'Amber Standard', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Horizon product page.', 'BP-IF-0002', 'manufacturer_page', 5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', 'HZ AM STD'),
('BP-IF-1003', 'Infraset', 'infraset', 'Roof tiles', 'Horizon Red Standard', 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 5 kg. 10.42 tiles/m2. Minimum pitch 17 degrees.', 'Red Standard', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Horizon product page.', 'BP-IF-0002', 'manufacturer_page', 5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', 'HZ RE STD'),
('BP-IF-1004', 'Infraset', 'infraset', 'Roof tiles', 'Horizon Slate Standard', 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 5 kg. 10.42 tiles/m2. Minimum pitch 17 degrees.', 'Slate Standard', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Horizon product page.', 'BP-IF-0002', 'manufacturer_page', 5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', 'HZ SL STD'),
('BP-IF-1005', 'Infraset', 'infraset', 'Roof tiles', 'Horizon Terracotta Standard', 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 5 kg. 10.42 tiles/m2. Minimum pitch 17 degrees.', 'Terracotta Standard', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Horizon product page.', 'BP-IF-0002', 'manufacturer_page', 5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', 'HZ TC STD'),
('BP-IF-1006', 'Infraset', 'infraset', 'Roof tiles', 'Horizon Dolomite Standard', 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 5 kg. 10.42 tiles/m2. Minimum pitch 17 degrees.', 'Dolomite Standard', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Dolomite is available on request, with a lead time and a minimum order.', 'BP-IF-0002', 'manufacturer_page', 5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', 'HZ DO STD'),
('BP-IF-1007', 'Infraset', 'infraset', 'Roof tiles', 'Horizon Brown Vintage', 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 5 kg. 10.42 tiles/m2. Minimum pitch 17 degrees.', 'Brown Vintage', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Horizon product page.', 'BP-IF-0002', 'manufacturer_page', 5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', 'HZ BR VT'),
('BP-IF-1008', 'Infraset', 'infraset', 'Roof tiles', 'Horizon Amber Vintage', 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 5 kg. 10.42 tiles/m2. Minimum pitch 17 degrees.', 'Amber Vintage', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Horizon product page.', 'BP-IF-0002', 'manufacturer_page', 5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', 'HZ AM VT'),
('BP-IF-1009', 'Infraset', 'infraset', 'Roof tiles', 'Horizon Red Vintage', 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 5 kg. 10.42 tiles/m2. Minimum pitch 17 degrees.', 'Red Vintage', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Horizon product page.', 'BP-IF-0002', 'manufacturer_page', 5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', 'HZ RE VT'),
('BP-IF-1010', 'Infraset', 'infraset', 'Roof tiles', 'Horizon Slate Vintage', 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 5 kg. 10.42 tiles/m2. Minimum pitch 17 degrees.', 'Slate Vintage', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Horizon product page.', 'BP-IF-0002', 'manufacturer_page', 5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', 'HZ SL VT'),
('BP-IF-1011', 'Infraset', 'infraset', 'Roof tiles', 'Horizon Terracotta Vintage', 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 5 kg. 10.42 tiles/m2. Minimum pitch 17 degrees.', 'Terracotta Vintage', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Horizon product page.', 'BP-IF-0002', 'manufacturer_page', 5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', 'HZ TC VT'),
('BP-IF-1012', 'Infraset', 'infraset', 'Roof tiles', 'Horizon Dolomite Vintage', 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 5 kg. 10.42 tiles/m2. Minimum pitch 17 degrees.', 'Dolomite Vintage', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Dolomite is available on request, with a lead time and a minimum order.', 'BP-IF-0002', 'manufacturer_page', 5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/horizon-concrete-shingle-tile/', 'HZ DO VT'),
('BP-IF-1013', 'Infraset', 'infraset', 'Roof tiles', 'Sunset Double Roman Brown Standard', 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 4.5 kg. 10.42 tiles/m2. Pitch 17 to 25 degrees.', 'Brown Standard', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Sunset product page. Mass on that page is 4.5 kg. SANS 677 is stated on the Horizon page as applying to Infraset building products.', 'BP-IF-0003', 'manufacturer_page', 4.5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', 'SS BR STD'),
('BP-IF-1014', 'Infraset', 'infraset', 'Roof tiles', 'Sunset Double Roman Amber Standard', 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 4.5 kg. 10.42 tiles/m2. Pitch 17 to 25 degrees.', 'Amber Standard', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Sunset product page. Mass on that page is 4.5 kg. SANS 677 is stated on the Horizon page as applying to Infraset building products.', 'BP-IF-0003', 'manufacturer_page', 4.5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', 'SS AM STD'),
('BP-IF-1015', 'Infraset', 'infraset', 'Roof tiles', 'Sunset Double Roman Red Standard', 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 4.5 kg. 10.42 tiles/m2. Pitch 17 to 25 degrees.', 'Red Standard', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Sunset product page. Mass on that page is 4.5 kg. SANS 677 is stated on the Horizon page as applying to Infraset building products.', 'BP-IF-0003', 'manufacturer_page', 4.5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', 'SS RE STD'),
('BP-IF-1016', 'Infraset', 'infraset', 'Roof tiles', 'Sunset Double Roman Slate Standard', 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 4.5 kg. 10.42 tiles/m2. Pitch 17 to 25 degrees.', 'Slate Standard', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Sunset product page. Mass on that page is 4.5 kg. SANS 677 is stated on the Horizon page as applying to Infraset building products.', 'BP-IF-0003', 'manufacturer_page', 4.5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', 'SS SL STD'),
('BP-IF-1017', 'Infraset', 'infraset', 'Roof tiles', 'Sunset Double Roman Terracotta Standard', 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 4.5 kg. 10.42 tiles/m2. Pitch 17 to 25 degrees.', 'Terracotta Standard', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Sunset product page. Mass on that page is 4.5 kg. SANS 677 is stated on the Horizon page as applying to Infraset building products.', 'BP-IF-0003', 'manufacturer_page', 4.5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', 'SS TC STD'),
('BP-IF-1018', 'Infraset', 'infraset', 'Roof tiles', 'Sunset Double Roman Dolomite Standard', 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 4.5 kg. 10.42 tiles/m2. Pitch 17 to 25 degrees.', 'Dolomite Standard', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Dolomite is marked available on request. SANS 677 is stated on the Horizon page as applying to Infraset building products.', 'BP-IF-0003', 'manufacturer_page', 4.5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', 'SS DO STD'),
('BP-IF-1019', 'Infraset', 'infraset', 'Roof tiles', 'Sunset Double Roman Brown Vintage', 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 4.5 kg. 10.42 tiles/m2. Pitch 17 to 25 degrees.', 'Brown Vintage', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Sunset product page. Mass on that page is 4.5 kg. SANS 677 is stated on the Horizon page as applying to Infraset building products.', 'BP-IF-0003', 'manufacturer_page', 4.5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', 'SS BR VT'),
('BP-IF-1020', 'Infraset', 'infraset', 'Roof tiles', 'Sunset Double Roman Amber Vintage', 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 4.5 kg. 10.42 tiles/m2. Pitch 17 to 25 degrees.', 'Amber Vintage', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Sunset product page. Mass on that page is 4.5 kg. SANS 677 is stated on the Horizon page as applying to Infraset building products.', 'BP-IF-0003', 'manufacturer_page', 4.5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', 'SS AM VT'),
('BP-IF-1021', 'Infraset', 'infraset', 'Roof tiles', 'Sunset Double Roman Red Vintage', 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 4.5 kg. 10.42 tiles/m2. Pitch 17 to 25 degrees.', 'Red Vintage', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Sunset product page. Mass on that page is 4.5 kg. SANS 677 is stated on the Horizon page as applying to Infraset building products.', 'BP-IF-0003', 'manufacturer_page', 4.5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', 'SS RE VT'),
('BP-IF-1022', 'Infraset', 'infraset', 'Roof tiles', 'Sunset Double Roman Slate Vintage', 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 4.5 kg. 10.42 tiles/m2. Pitch 17 to 25 degrees.', 'Slate Vintage', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Sunset product page. Mass on that page is 4.5 kg. SANS 677 is stated on the Horizon page as applying to Infraset building products.', 'BP-IF-0003', 'manufacturer_page', 4.5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', 'SS SL VT'),
('BP-IF-1023', 'Infraset', 'infraset', 'Roof tiles', 'Sunset Double Roman Terracotta Vintage', 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 4.5 kg. 10.42 tiles/m2. Pitch 17 to 25 degrees.', 'Terracotta Vintage', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Colour and code published on the Sunset product page. Mass on that page is 4.5 kg. SANS 677 is stated on the Horizon page as applying to Infraset building products.', 'BP-IF-0003', 'manufacturer_page', 4.5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', 'SS TC VT'),
('BP-IF-1024', 'Infraset', 'infraset', 'Roof tiles', 'Sunset Double Roman Dolomite Vintage', 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', '420 x 330 mm overall. Effective width 300 mm. Mass 4.5 kg. 10.42 tiles/m2. Pitch 17 to 25 degrees.', 'Dolomite Vintage', 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Dolomite is marked available on request. SANS 677 is stated on the Horizon page as applying to Infraset building products.', 'BP-IF-0003', 'manufacturer_page', 4.5, 10.42, null, null, 'https://infraset.co.za/roof-tiles/sunset-double-roman-concrete-bold-roll-tile/', 'SS DO VT'),
('BP-IF-1025', 'Infraset', 'infraset', 'Roof tiles', 'Sunrise 4.4', 'https://infraset.co.za/', null, null, 'SANS 677', null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'permission_required', 'sourced_quote_only', 'manufacturer_page', 'Named on the Infraset home page as a deep roll tile. Size and colours were not on the page that was read, so they are not filled in.', 'BP-IF-0001', 'manufacturer_page', null, null, null, null, 'https://infraset.co.za/', null)
on conflict (sku) do update set
  name = excluded.name,
  dimensions = excluded.dimensions,
  colour_finish = excluded.colour_finish,
  standard_ref = excluded.standard_ref,
  notes = excluded.notes,
  parent_sku = excluded.parent_sku,
  spec_status = excluded.spec_status,
  mass_kg = excluded.mass_kg,
  units_per_m2 = excluded.units_per_m2,
  units_per_pallet = excluded.units_per_pallet,
  factory = excluded.factory,
  source_url = excluded.source_url,
  manufacturer_code = excluded.manufacturer_code;

update brand_skus
set notes = 'Vintage finishes are the VT codes published on the Horizon and Sunset pages, not a separate size.'
where sku = 'BP-IF-0004';
