-- Named products that appear on the manufacturer pages in the brand-shop image library.
-- No size is stored. The photograph lives in the app, not in this table.

insert into brand_skus (
  sku, brand, brand_slug, family, name, official_url, dimensions, colour_finish, standard_ref, brochure_ref,
  availability_status, delivery_class, image_rights_status, publication_status, source_status, notes,
  parent_sku, spec_status, mass_kg, units_per_m2, units_per_pallet, factory, source_url, manufacturer_code
) values
('BP-CB-1019', 'Corobrik', 'corobrik', 'Clay face bricks', 'Autumn Wheat Travertine', 'https://www.corobrik.co.za/clay-face-brick-range', null, 'Autumn Wheat Travertine', null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'manufacturer_site', 'sourced_quote_only', 'manufacturer_page', 'Named on the Corobrik face-brick page. The swatch is theirs. No size from that page is stored here.', 'BP-CB-0001', 'brochure_name_only', null, null, null, null, 'https://www.corobrik.co.za/clay-face-brick-range', null),
('BP-BS-1019', 'Bosun', 'bosun', 'Paving', 'Bevel Bond', 'https://www.bosun.co.za/products/paving/', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'manufacturer_site', 'sourced_quote_only', 'manufacturer_page', 'Named on the Bosun paving page. The driveway photograph is theirs. No size is stored.', 'BP-BS-0001', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/paving/', null),
('BP-BS-1020', 'Bosun', 'bosun', 'Retaining walls', 'Retaining Rock', 'https://www.bosun.co.za/products/retaining-wall-blocks/', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'manufacturer_site', 'sourced_quote_only', 'manufacturer_page', 'Named on the Bosun retaining page. No size is stored.', 'BP-BS-0003', 'manufacturer_page', null, null, null, null, 'https://www.bosun.co.za/products/retaining-wall-blocks/', null),
('BP-IF-1026', 'Infraset', 'infraset', 'Paving', 'Bush Stone', 'https://infraset.co.za/paving/', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'manufacturer_site', 'sourced_quote_only', 'manufacturer_page', 'Named on the Infraset paving page. No size is stored.', 'BP-IF-0005', 'manufacturer_page', null, null, null, null, 'https://infraset.co.za/paving/', null),
('BP-IF-1027', 'Infraset', 'infraset', 'Paving', 'Cottage Stone', 'https://infraset.co.za/paving/', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'manufacturer_site', 'sourced_quote_only', 'manufacturer_page', 'Named on the Infraset paving page. No size is stored.', 'BP-IF-0005', 'manufacturer_page', null, null, null, null, 'https://infraset.co.za/paving/', null),
('BP-IF-1028', 'Infraset', 'infraset', 'Paving', 'Masonique', 'https://infraset.co.za/paving/', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'manufacturer_site', 'sourced_quote_only', 'manufacturer_page', 'Named on the Infraset paving page. No size is stored.', 'BP-IF-0005', 'manufacturer_page', null, null, null, null, 'https://infraset.co.za/paving/', null),
('BP-IF-1029', 'Infraset', 'infraset', 'Retaining walls', 'Infrablok 350', 'https://infraset.co.za/retaining-walls/', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'manufacturer_site', 'sourced_quote_only', 'manufacturer_page', 'Named on the Infraset retaining page. No size is stored.', 'BP-IF-0006', 'manufacturer_page', null, null, null, null, 'https://infraset.co.za/retaining-walls/', null),
('BP-IF-1030', 'Infraset', 'infraset', 'Retaining walls', 'Infrablok 425', 'https://infraset.co.za/retaining-walls/', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'manufacturer_site', 'sourced_quote_only', 'manufacturer_page', 'Named on the Infraset retaining page. No size is stored.', 'BP-IF-0006', 'manufacturer_page', null, null, null, null, 'https://infraset.co.za/retaining-walls/', null),
('BP-IF-1031', 'Infraset', 'infraset', 'Retaining walls', 'Löffelstein', 'https://infraset.co.za/retaining-walls/', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'manufacturer_site', 'sourced_quote_only', 'manufacturer_page', 'Named on the Infraset retaining page. No size is stored.', 'BP-IF-0006', 'manufacturer_page', null, null, null, null, 'https://infraset.co.za/retaining-walls/', null),
('BP-IF-1032', 'Infraset', 'infraset', 'Retaining walls', 'Ridgeblok', 'https://infraset.co.za/retaining-walls/', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'manufacturer_site', 'sourced_quote_only', 'manufacturer_page', 'Named on the Infraset retaining page. No size is stored.', 'BP-IF-0006', 'manufacturer_page', null, null, null, null, 'https://infraset.co.za/retaining-walls/', null),
('BP-IF-1033', 'Infraset', 'infraset', 'Erosion control', 'Eco-Link', 'https://infraset.co.za/erosion-control/', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'manufacturer_site', 'sourced_quote_only', 'manufacturer_page', 'Named on the Infraset erosion-control page. No size is stored.', 'BP-IF-0007', 'manufacturer_page', null, null, null, null, 'https://infraset.co.za/erosion-control/', null),
('BP-IF-1034', 'Infraset', 'infraset', 'Erosion control', 'Infralok 150', 'https://infraset.co.za/erosion-control/', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'manufacturer_site', 'sourced_quote_only', 'manufacturer_page', 'Named on the Infraset erosion-control page. No size is stored.', 'BP-IF-0007', 'manufacturer_page', null, null, null, null, 'https://infraset.co.za/erosion-control/', null),
('BP-IF-1035', 'Infraset', 'infraset', 'Erosion control', 'Geo-Link', 'https://infraset.co.za/erosion-control/', null, null, null, null, 'manufacturer_confirmation_required', 'heavy_or_quote_required', 'manufacturer_site', 'sourced_quote_only', 'manufacturer_page', 'Named on the Infraset erosion-control page. No size is stored.', 'BP-IF-0007', 'manufacturer_page', null, null, null, null, 'https://infraset.co.za/erosion-control/', null)
on conflict (sku) do update set
  name = excluded.name,
  family = excluded.family,
  parent_sku = excluded.parent_sku,
  official_url = excluded.official_url,
  source_url = excluded.source_url,
  colour_finish = excluded.colour_finish,
  notes = excluded.notes,
  spec_status = excluded.spec_status,
  image_rights_status = excluded.image_rights_status;
