/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as BrandsRouteImport } from './routes/brands'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeliveryReachRouteImport } from './routes/delivery-reach'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HealthzRouteImport } from './routes/healthz'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ResponsibleSourcingRouteImport } from './routes/responsible-sourcing'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as RfqRouteImport } from './routes/rfq'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as WaysToPayRouteImport } from './routes/ways-to-pay'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BrandsSlugRouteImport } from './routes/brands.$slug'
import { Route as BundlesSlugRouteImport } from './routes/bundles.$slug'
import { Route as DeskIndexRouteImport } from './routes/desk.index'
import { Route as DeskBrandsRouteImport } from './routes/desk.brands'
import { Route as DeskCustomersRouteImport } from './routes/desk.customers'
import { Route as DeskInboxRouteImport } from './routes/desk.inbox'
import { Route as DeskInventoryRouteImport } from './routes/desk.inventory'
import { Route as DeskJournalRouteImport } from './routes/desk.journal'
import { Route as DeskLeadsRouteImport } from './routes/desk.leads'
import { Route as DeskLogisticsRouteImport } from './routes/desk.logistics'
import { Route as DeskOrdersRouteImport } from './routes/desk.orders'
import { Route as DeskPricingRouteImport } from './routes/desk.pricing'
import { Route as DeskPromotionsRouteImport } from './routes/desk.promotions'
import { Route as DeskQuestionsRouteImport } from './routes/desk.questions'
import { Route as DeskReportsRouteImport } from './routes/desk.reports'
import { Route as DeskReturnsRouteImport } from './routes/desk.returns'
import { Route as DeskReviewsRouteImport } from './routes/desk.reviews'
import { Route as DeskRfqsRouteImport } from './routes/desk.rfqs'
import { Route as DivisionsSlugRouteImport } from './routes/divisions.$slug'
import { Route as InvoiceIdRouteImport } from './routes/invoice.$id'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ProductSkuRouteImport } from './routes/product.$sku'
import { Route as SectorsSlugRouteImport } from './routes/sectors.$slug'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as SpecSkuRouteImport } from './routes/spec.$sku'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as MediaPostsSlugRouteImport } from './routes/media.posts.$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsRoute = BrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveryReachRoute = DeliveryReachRouteImport.update({
  id: '/delivery-reach',
  path: '/delivery-reach',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthzRoute = HealthzRouteImport.update({
  id: '/healthz',
  path: '/healthz',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ResponsibleSourcingRoute = ResponsibleSourcingRouteImport.update({
  id: '/responsible-sourcing',
  path: '/responsible-sourcing',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqRoute = RfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const WaysToPayRoute = WaysToPayRouteImport.update({
  id: '/ways-to-pay',
  path: '/ways-to-pay',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BrandsRoute,
} as any)
const BrandsSlugRoute = BrandsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BrandsRoute,
} as any)
const BundlesSlugRoute = BundlesSlugRouteImport.update({
  id: '/bundles/$slug',
  path: '/bundles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskBrandsRoute = DeskBrandsRouteImport.update({
  id: '/brands',
  path: '/brands',
  getParentRoute: () => DeskRoute,
} as any)
const DeskCustomersRoute = DeskCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DeskRoute,
} as any)
const DeskInboxRoute = DeskInboxRouteImport.update({
  id: '/inbox',
  path: '/inbox',
  getParentRoute: () => DeskRoute,
} as any)
const DeskInventoryRoute = DeskInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DeskRoute,
} as any)
const DeskJournalRoute = DeskJournalRouteImport.update({
  id: '/journal',
  path: '/journal',
  getParentRoute: () => DeskRoute,
} as any)
const DeskLeadsRoute = DeskLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => DeskRoute,
} as any)
const DeskLogisticsRoute = DeskLogisticsRouteImport.update({
  id: '/logistics',
  path: '/logistics',
  getParentRoute: () => DeskRoute,
} as any)
const DeskOrdersRoute = DeskOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DeskRoute,
} as any)
const DeskPricingRoute = DeskPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DeskRoute,
} as any)
const DeskPromotionsRoute = DeskPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => DeskRoute,
} as any)
const DeskQuestionsRoute = DeskQuestionsRouteImport.update({
  id: '/questions',
  path: '/questions',
  getParentRoute: () => DeskRoute,
} as any)
const DeskReportsRoute = DeskReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DeskRoute,
} as any)
const DeskReturnsRoute = DeskReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => DeskRoute,
} as any)
const DeskReviewsRoute = DeskReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DeskRoute,
} as any)
const DeskRfqsRoute = DeskRfqsRouteImport.update({
  id: '/rfqs',
  path: '/rfqs',
  getParentRoute: () => DeskRoute,
} as any)
const DivisionsSlugRoute = DivisionsSlugRouteImport.update({
  id: '/divisions/$slug',
  path: '/divisions/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoiceIdRoute = InvoiceIdRouteImport.update({
  id: '/invoice/$id',
  path: '/invoice/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSkuRoute = ProductSkuRouteImport.update({
  id: '/product/$sku',
  path: '/product/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsSlugRoute = SectorsSlugRouteImport.update({
  id: '/sectors/$slug',
  path: '/sectors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const SpecSkuRoute = SpecSkuRouteImport.update({
  id: '/spec/$sku',
  path: '/spec/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const MediaPostsSlugRoute = MediaPostsSlugRouteImport.update({
  id: '/media/posts/$slug',
  path: '/media/posts/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRouteWithChildren
  '/brands': typeof BrandsRouteWithChildren
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/delivery-reach': typeof DeliveryReachRoute
  '/desk': typeof DeskRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/healthz': typeof HealthzRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/partners': typeof PartnersRoute
  '/projects': typeof ProjectsRoute
  '/responsible-sourcing': typeof ResponsibleSourcingRoute
  '/returns': typeof ReturnsRoute
  '/rfq': typeof RfqRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/track': typeof TrackRoute
  '/trade': typeof TradeRoute
  '/warranty': typeof WarrantyRoute
  '/ways-to-pay': typeof WaysToPayRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/bundles/$slug': typeof BundlesSlugRoute
  '/desk/brands': typeof DeskBrandsRoute
  '/desk/customers': typeof DeskCustomersRoute
  '/desk/inbox': typeof DeskInboxRoute
  '/desk/inventory': typeof DeskInventoryRoute
  '/desk/journal': typeof DeskJournalRoute
  '/desk/leads': typeof DeskLeadsRoute
  '/desk/logistics': typeof DeskLogisticsRoute
  '/desk/orders': typeof DeskOrdersRoute
  '/desk/pricing': typeof DeskPricingRoute
  '/desk/promotions': typeof DeskPromotionsRoute
  '/desk/questions': typeof DeskQuestionsRoute
  '/desk/reports': typeof DeskReportsRoute
  '/desk/returns': typeof DeskReturnsRoute
  '/desk/reviews': typeof DeskReviewsRoute
  '/desk/rfqs': typeof DeskRfqsRoute
  '/divisions/$slug': typeof DivisionsSlugRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$sku': typeof ProductSkuRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/spec/$sku': typeof SpecSkuRoute
  '/blog/': typeof BlogIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/media/posts/$slug': typeof MediaPostsSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/delivery-reach': typeof DeliveryReachRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/healthz': typeof HealthzRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/partners': typeof PartnersRoute
  '/projects': typeof ProjectsRoute
  '/responsible-sourcing': typeof ResponsibleSourcingRoute
  '/returns': typeof ReturnsRoute
  '/rfq': typeof RfqRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/track': typeof TrackRoute
  '/trade': typeof TradeRoute
  '/warranty': typeof WarrantyRoute
  '/ways-to-pay': typeof WaysToPayRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/bundles/$slug': typeof BundlesSlugRoute
  '/desk/brands': typeof DeskBrandsRoute
  '/desk/customers': typeof DeskCustomersRoute
  '/desk/inbox': typeof DeskInboxRoute
  '/desk/inventory': typeof DeskInventoryRoute
  '/desk/journal': typeof DeskJournalRoute
  '/desk/leads': typeof DeskLeadsRoute
  '/desk/logistics': typeof DeskLogisticsRoute
  '/desk/orders': typeof DeskOrdersRoute
  '/desk/pricing': typeof DeskPricingRoute
  '/desk/promotions': typeof DeskPromotionsRoute
  '/desk/questions': typeof DeskQuestionsRoute
  '/desk/reports': typeof DeskReportsRoute
  '/desk/returns': typeof DeskReturnsRoute
  '/desk/reviews': typeof DeskReviewsRoute
  '/desk/rfqs': typeof DeskRfqsRoute
  '/divisions/$slug': typeof DivisionsSlugRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$sku': typeof ProductSkuRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/spec/$sku': typeof SpecSkuRoute
  '/blog': typeof BlogIndexRoute
  '/brands': typeof BrandsIndexRoute
  '/desk': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/media/posts/$slug': typeof MediaPostsSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRouteWithChildren
  '/brands': typeof BrandsRouteWithChildren
  '/careers': typeof CareersRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/delivery-reach': typeof DeliveryReachRoute
  '/desk': typeof DeskRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/healthz': typeof HealthzRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/partners': typeof PartnersRoute
  '/projects': typeof ProjectsRoute
  '/responsible-sourcing': typeof ResponsibleSourcingRoute
  '/returns': typeof ReturnsRoute
  '/rfq': typeof RfqRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/track': typeof TrackRoute
  '/trade': typeof TradeRoute
  '/warranty': typeof WarrantyRoute
  '/ways-to-pay': typeof WaysToPayRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brands/$slug': typeof BrandsSlugRoute
  '/bundles/$slug': typeof BundlesSlugRoute
  '/desk/brands': typeof DeskBrandsRoute
  '/desk/customers': typeof DeskCustomersRoute
  '/desk/inbox': typeof DeskInboxRoute
  '/desk/inventory': typeof DeskInventoryRoute
  '/desk/journal': typeof DeskJournalRoute
  '/desk/leads': typeof DeskLeadsRoute
  '/desk/logistics': typeof DeskLogisticsRoute
  '/desk/orders': typeof DeskOrdersRoute
  '/desk/pricing': typeof DeskPricingRoute
  '/desk/promotions': typeof DeskPromotionsRoute
  '/desk/questions': typeof DeskQuestionsRoute
  '/desk/reports': typeof DeskReportsRoute
  '/desk/returns': typeof DeskReturnsRoute
  '/desk/reviews': typeof DeskReviewsRoute
  '/desk/rfqs': typeof DeskRfqsRoute
  '/divisions/$slug': typeof DivisionsSlugRoute
  '/invoice/$id': typeof InvoiceIdRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$sku': typeof ProductSkuRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/spec/$sku': typeof SpecSkuRoute
  '/blog/': typeof BlogIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/desk/': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/media/posts/$slug': typeof MediaPostsSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/account'
    | '/blog'
    | '/brands'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/delivery-reach'
    | '/desk'
    | '/forgot-password'
    | '/healthz'
    | '/help'
    | '/login'
    | '/new'
    | '/partners'
    | '/projects'
    | '/responsible-sourcing'
    | '/returns'
    | '/rfq'
    | '/search'
    | '/shop'
    | '/sitemap'
    | '/track'
    | '/trade'
    | '/warranty'
    | '/ways-to-pay'
    | '/blog/$slug'
    | '/brands/$slug'
    | '/bundles/$slug'
    | '/desk/brands'
    | '/desk/customers'
    | '/desk/inbox'
    | '/desk/inventory'
    | '/desk/journal'
    | '/desk/leads'
    | '/desk/logistics'
    | '/desk/orders'
    | '/desk/pricing'
    | '/desk/promotions'
    | '/desk/questions'
    | '/desk/reports'
    | '/desk/returns'
    | '/desk/reviews'
    | '/desk/rfqs'
    | '/divisions/$slug'
    | '/invoice/$id'
    | '/legal/$slug'
    | '/locations/$slug'
    | '/order/$id'
    | '/product/$sku'
    | '/sectors/$slug'
    | '/shop/$slug'
    | '/spec/$sku'
    | '/blog/'
    | '/brands/'
    | '/desk/'
    | '/api/auth/$'
    | '/media/posts/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/account'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/delivery-reach'
    | '/forgot-password'
    | '/healthz'
    | '/help'
    | '/login'
    | '/new'
    | '/partners'
    | '/projects'
    | '/responsible-sourcing'
    | '/returns'
    | '/rfq'
    | '/search'
    | '/shop'
    | '/sitemap'
    | '/track'
    | '/trade'
    | '/warranty'
    | '/ways-to-pay'
    | '/blog/$slug'
    | '/brands/$slug'
    | '/bundles/$slug'
    | '/desk/brands'
    | '/desk/customers'
    | '/desk/inbox'
    | '/desk/inventory'
    | '/desk/journal'
    | '/desk/leads'
    | '/desk/logistics'
    | '/desk/orders'
    | '/desk/pricing'
    | '/desk/promotions'
    | '/desk/questions'
    | '/desk/reports'
    | '/desk/returns'
    | '/desk/reviews'
    | '/desk/rfqs'
    | '/divisions/$slug'
    | '/invoice/$id'
    | '/legal/$slug'
    | '/locations/$slug'
    | '/order/$id'
    | '/product/$sku'
    | '/sectors/$slug'
    | '/shop/$slug'
    | '/spec/$sku'
    | '/blog'
    | '/brands'
    | '/desk'
    | '/api/auth/$'
    | '/media/posts/$slug'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/account'
    | '/blog'
    | '/brands'
    | '/careers'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/delivery-reach'
    | '/desk'
    | '/forgot-password'
    | '/healthz'
    | '/help'
    | '/login'
    | '/new'
    | '/partners'
    | '/projects'
    | '/responsible-sourcing'
    | '/returns'
    | '/rfq'
    | '/search'
    | '/shop'
    | '/sitemap'
    | '/track'
    | '/trade'
    | '/warranty'
    | '/ways-to-pay'
    | '/blog/$slug'
    | '/brands/$slug'
    | '/bundles/$slug'
    | '/desk/brands'
    | '/desk/customers'
    | '/desk/inbox'
    | '/desk/inventory'
    | '/desk/journal'
    | '/desk/leads'
    | '/desk/logistics'
    | '/desk/orders'
    | '/desk/pricing'
    | '/desk/promotions'
    | '/desk/questions'
    | '/desk/reports'
    | '/desk/returns'
    | '/desk/reviews'
    | '/desk/rfqs'
    | '/divisions/$slug'
    | '/invoice/$id'
    | '/legal/$slug'
    | '/locations/$slug'
    | '/order/$id'
    | '/product/$sku'
    | '/sectors/$slug'
    | '/shop/$slug'
    | '/spec/$sku'
    | '/blog/'
    | '/brands/'
    | '/desk/'
    | '/api/auth/$'
    | '/media/posts/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AccountRoute: typeof AccountRoute
  BlogRoute: typeof BlogRouteWithChildren
  BrandsRoute: typeof BrandsRouteWithChildren
  CareersRoute: typeof CareersRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  DeliveryReachRoute: typeof DeliveryReachRoute
  DeskRoute: typeof DeskRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HealthzRoute: typeof HealthzRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  PartnersRoute: typeof PartnersRoute
  ProjectsRoute: typeof ProjectsRoute
  ResponsibleSourcingRoute: typeof ResponsibleSourcingRoute
  ReturnsRoute: typeof ReturnsRoute
  RfqRoute: typeof RfqRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRouteWithChildren
  SitemapRoute: typeof SitemapRoute
  TrackRoute: typeof TrackRoute
  TradeRoute: typeof TradeRoute
  WarrantyRoute: typeof WarrantyRoute
  WaysToPayRoute: typeof WaysToPayRoute
  BundlesSlugRoute: typeof BundlesSlugRoute
  DivisionsSlugRoute: typeof DivisionsSlugRoute
  InvoiceIdRoute: typeof InvoiceIdRoute
  LegalSlugRoute: typeof LegalSlugRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductSkuRoute: typeof ProductSkuRoute
  SectorsSlugRoute: typeof SectorsSlugRoute
  SpecSkuRoute: typeof SpecSkuRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  MediaPostsSlugRoute: typeof MediaPostsSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands': {
      id: '/brands'
      path: '/brands'
      fullPath: '/brands'
      preLoaderRoute: typeof BrandsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/delivery-reach': {
      id: '/delivery-reach'
      path: '/delivery-reach'
      fullPath: '/delivery-reach'
      preLoaderRoute: typeof DeliveryReachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healthz': {
      id: '/healthz'
      path: '/healthz'
      fullPath: '/healthz'
      preLoaderRoute: typeof HealthzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/responsible-sourcing': {
      id: '/responsible-sourcing'
      path: '/responsible-sourcing'
      fullPath: '/responsible-sourcing'
      preLoaderRoute: typeof ResponsibleSourcingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq': {
      id: '/rfq'
      path: '/rfq'
      fullPath: '/rfq'
      preLoaderRoute: typeof RfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ways-to-pay': {
      id: '/ways-to-pay'
      path: '/ways-to-pay'
      fullPath: '/ways-to-pay'
      preLoaderRoute: typeof WaysToPayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/brands/': {
      id: '/brands/'
      path: '/'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/brands/$slug': {
      id: '/brands/$slug'
      path: '/$slug'
      fullPath: '/brands/$slug'
      preLoaderRoute: typeof BrandsSlugRouteImport
      parentRoute: typeof BrandsRoute
    }
    '/bundles/$slug': {
      id: '/bundles/$slug'
      path: '/bundles/$slug'
      fullPath: '/bundles/$slug'
      preLoaderRoute: typeof BundlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/brands': {
      id: '/desk/brands'
      path: '/brands'
      fullPath: '/desk/brands'
      preLoaderRoute: typeof DeskBrandsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/customers': {
      id: '/desk/customers'
      path: '/customers'
      fullPath: '/desk/customers'
      preLoaderRoute: typeof DeskCustomersRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/inbox': {
      id: '/desk/inbox'
      path: '/inbox'
      fullPath: '/desk/inbox'
      preLoaderRoute: typeof DeskInboxRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/inventory': {
      id: '/desk/inventory'
      path: '/inventory'
      fullPath: '/desk/inventory'
      preLoaderRoute: typeof DeskInventoryRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/journal': {
      id: '/desk/journal'
      path: '/journal'
      fullPath: '/desk/journal'
      preLoaderRoute: typeof DeskJournalRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/leads': {
      id: '/desk/leads'
      path: '/leads'
      fullPath: '/desk/leads'
      preLoaderRoute: typeof DeskLeadsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/logistics': {
      id: '/desk/logistics'
      path: '/logistics'
      fullPath: '/desk/logistics'
      preLoaderRoute: typeof DeskLogisticsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/orders': {
      id: '/desk/orders'
      path: '/orders'
      fullPath: '/desk/orders'
      preLoaderRoute: typeof DeskOrdersRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/pricing': {
      id: '/desk/pricing'
      path: '/pricing'
      fullPath: '/desk/pricing'
      preLoaderRoute: typeof DeskPricingRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/promotions': {
      id: '/desk/promotions'
      path: '/promotions'
      fullPath: '/desk/promotions'
      preLoaderRoute: typeof DeskPromotionsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/questions': {
      id: '/desk/questions'
      path: '/questions'
      fullPath: '/desk/questions'
      preLoaderRoute: typeof DeskQuestionsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/reports': {
      id: '/desk/reports'
      path: '/reports'
      fullPath: '/desk/reports'
      preLoaderRoute: typeof DeskReportsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/returns': {
      id: '/desk/returns'
      path: '/returns'
      fullPath: '/desk/returns'
      preLoaderRoute: typeof DeskReturnsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/reviews': {
      id: '/desk/reviews'
      path: '/reviews'
      fullPath: '/desk/reviews'
      preLoaderRoute: typeof DeskReviewsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/rfqs': {
      id: '/desk/rfqs'
      path: '/rfqs'
      fullPath: '/desk/rfqs'
      preLoaderRoute: typeof DeskRfqsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/divisions/$slug': {
      id: '/divisions/$slug'
      path: '/divisions/$slug'
      fullPath: '/divisions/$slug'
      preLoaderRoute: typeof DivisionsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoice/$id': {
      id: '/invoice/$id'
      path: '/invoice/$id'
      fullPath: '/invoice/$id'
      preLoaderRoute: typeof InvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$sku': {
      id: '/product/$sku'
      path: '/product/$sku'
      fullPath: '/product/$sku'
      preLoaderRoute: typeof ProductSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/$slug': {
      id: '/sectors/$slug'
      path: '/sectors/$slug'
      fullPath: '/sectors/$slug'
      preLoaderRoute: typeof SectorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/spec/$sku': {
      id: '/spec/$sku'
      path: '/spec/$sku'
      fullPath: '/spec/$sku'
      preLoaderRoute: typeof SpecSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/media/posts/$slug': {
      id: '/media/posts/$slug'
      path: '/media/posts/$slug'
      fullPath: '/media/posts/$slug'
      preLoaderRoute: typeof MediaPostsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface BrandsRouteChildren {
  BrandsSlugRoute: typeof BrandsSlugRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
}

const BrandsRouteChildren: BrandsRouteChildren = {
  BrandsSlugRoute: BrandsSlugRoute,
  BrandsIndexRoute: BrandsIndexRoute,
}

const BrandsRouteWithChildren =
  BrandsRoute._addFileChildren(BrandsRouteChildren)

interface DeskRouteChildren {
  DeskBrandsRoute: typeof DeskBrandsRoute
  DeskCustomersRoute: typeof DeskCustomersRoute
  DeskInboxRoute: typeof DeskInboxRoute
  DeskInventoryRoute: typeof DeskInventoryRoute
  DeskJournalRoute: typeof DeskJournalRoute
  DeskLeadsRoute: typeof DeskLeadsRoute
  DeskLogisticsRoute: typeof DeskLogisticsRoute
  DeskOrdersRoute: typeof DeskOrdersRoute
  DeskPricingRoute: typeof DeskPricingRoute
  DeskPromotionsRoute: typeof DeskPromotionsRoute
  DeskQuestionsRoute: typeof DeskQuestionsRoute
  DeskReportsRoute: typeof DeskReportsRoute
  DeskReturnsRoute: typeof DeskReturnsRoute
  DeskReviewsRoute: typeof DeskReviewsRoute
  DeskRfqsRoute: typeof DeskRfqsRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskBrandsRoute: DeskBrandsRoute,
  DeskCustomersRoute: DeskCustomersRoute,
  DeskInboxRoute: DeskInboxRoute,
  DeskInventoryRoute: DeskInventoryRoute,
  DeskJournalRoute: DeskJournalRoute,
  DeskLeadsRoute: DeskLeadsRoute,
  DeskLogisticsRoute: DeskLogisticsRoute,
  DeskOrdersRoute: DeskOrdersRoute,
  DeskPricingRoute: DeskPricingRoute,
  DeskPromotionsRoute: DeskPromotionsRoute,
  DeskQuestionsRoute: DeskQuestionsRoute,
  DeskReportsRoute: DeskReportsRoute,
  DeskReturnsRoute: DeskReturnsRoute,
  DeskReviewsRoute: DeskReviewsRoute,
  DeskRfqsRoute: DeskRfqsRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AccountRoute: AccountRoute,
  BlogRoute: BlogRouteWithChildren,
  BrandsRoute: BrandsRouteWithChildren,
  CareersRoute: CareersRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  DeliveryReachRoute: DeliveryReachRoute,
  DeskRoute: DeskRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HealthzRoute: HealthzRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  PartnersRoute: PartnersRoute,
  ProjectsRoute: ProjectsRoute,
  ResponsibleSourcingRoute: ResponsibleSourcingRoute,
  ReturnsRoute: ReturnsRoute,
  RfqRoute: RfqRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRouteWithChildren,
  SitemapRoute: SitemapRoute,
  TrackRoute: TrackRoute,
  TradeRoute: TradeRoute,
  WarrantyRoute: WarrantyRoute,
  WaysToPayRoute: WaysToPayRoute,
  BundlesSlugRoute: BundlesSlugRoute,
  DivisionsSlugRoute: DivisionsSlugRoute,
  InvoiceIdRoute: InvoiceIdRoute,
  LegalSlugRoute: LegalSlugRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  OrderIdRoute: OrderIdRoute,
  ProductSkuRoute: ProductSkuRoute,
  SectorsSlugRoute: SectorsSlugRoute,
  SpecSkuRoute: SpecSkuRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  MediaPostsSlugRoute: MediaPostsSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
