/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AccountRouteImport } from './routes/account'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CollectionsRouteImport } from './routes/collections'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeskRouteImport } from './routes/desk'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as HelpRouteImport } from './routes/help'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NewRouteImport } from './routes/new'
import { Route as PartnersRouteImport } from './routes/partners'
import { Route as ProjectsRouteImport } from './routes/projects'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as RfqRouteImport } from './routes/rfq'
import { Route as SearchRouteImport } from './routes/search'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as SitemapRouteImport } from './routes/sitemap'
import { Route as TrackRouteImport } from './routes/track'
import { Route as TradeRouteImport } from './routes/trade'
import { Route as WarrantyRouteImport } from './routes/warranty'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as BundlesSlugRouteImport } from './routes/bundles.$slug'
import { Route as DeskIndexRouteImport } from './routes/desk.index'
import { Route as DeskCustomersRouteImport } from './routes/desk.customers'
import { Route as DeskInventoryRouteImport } from './routes/desk.inventory'
import { Route as DeskOrdersRouteImport } from './routes/desk.orders'
import { Route as DeskPricingRouteImport } from './routes/desk.pricing'
import { Route as DeskPromotionsRouteImport } from './routes/desk.promotions'
import { Route as DeskReportsRouteImport } from './routes/desk.reports'
import { Route as DeskReviewsRouteImport } from './routes/desk.reviews'
import { Route as LegalSlugRouteImport } from './routes/legal.$slug'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as OrderIdRouteImport } from './routes/order.$id'
import { Route as ProductSkuRouteImport } from './routes/product.$sku'
import { Route as SectorsSlugRouteImport } from './routes/sectors.$slug'
import { Route as ShopSlugRouteImport } from './routes/shop.$slug'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionsRoute = CollectionsRouteImport.update({
  id: '/collections',
  path: '/collections',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskRoute = DeskRouteImport.update({
  id: '/desk',
  path: '/desk',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NewRoute = NewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRoute = PartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const RfqRoute = RfqRouteImport.update({
  id: '/rfq',
  path: '/rfq',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapRoute = SitemapRouteImport.update({
  id: '/sitemap',
  path: '/sitemap',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackRoute = TrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => rootRouteImport,
} as any)
const TradeRoute = TradeRouteImport.update({
  id: '/trade',
  path: '/trade',
  getParentRoute: () => rootRouteImport,
} as any)
const WarrantyRoute = WarrantyRouteImport.update({
  id: '/warranty',
  path: '/warranty',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const BundlesSlugRoute = BundlesSlugRouteImport.update({
  id: '/bundles/$slug',
  path: '/bundles/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const DeskIndexRoute = DeskIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DeskRoute,
} as any)
const DeskCustomersRoute = DeskCustomersRouteImport.update({
  id: '/customers',
  path: '/customers',
  getParentRoute: () => DeskRoute,
} as any)
const DeskInventoryRoute = DeskInventoryRouteImport.update({
  id: '/inventory',
  path: '/inventory',
  getParentRoute: () => DeskRoute,
} as any)
const DeskOrdersRoute = DeskOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => DeskRoute,
} as any)
const DeskPricingRoute = DeskPricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => DeskRoute,
} as any)
const DeskPromotionsRoute = DeskPromotionsRouteImport.update({
  id: '/promotions',
  path: '/promotions',
  getParentRoute: () => DeskRoute,
} as any)
const DeskReportsRoute = DeskReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DeskRoute,
} as any)
const DeskReviewsRoute = DeskReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DeskRoute,
} as any)
const LegalSlugRoute = LegalSlugRouteImport.update({
  id: '/legal/$slug',
  path: '/legal/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/locations/$slug',
  path: '/locations/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const OrderIdRoute = OrderIdRouteImport.update({
  id: '/order/$id',
  path: '/order/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductSkuRoute = ProductSkuRouteImport.update({
  id: '/product/$sku',
  path: '/product/$sku',
  getParentRoute: () => rootRouteImport,
} as any)
const SectorsSlugRoute = SectorsSlugRouteImport.update({
  id: '/sectors/$slug',
  path: '/sectors/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopSlugRoute = ShopSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ShopRoute,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/desk': typeof DeskRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/partners': typeof PartnersRoute
  '/projects': typeof ProjectsRoute
  '/returns': typeof ReturnsRoute
  '/rfq': typeof RfqRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/track': typeof TrackRoute
  '/trade': typeof TradeRoute
  '/warranty': typeof WarrantyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bundles/$slug': typeof BundlesSlugRoute
  '/desk/customers': typeof DeskCustomersRoute
  '/desk/inventory': typeof DeskInventoryRoute
  '/desk/orders': typeof DeskOrdersRoute
  '/desk/pricing': typeof DeskPricingRoute
  '/desk/promotions': typeof DeskPromotionsRoute
  '/desk/reports': typeof DeskReportsRoute
  '/desk/reviews': typeof DeskReviewsRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$sku': typeof ProductSkuRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/desk/': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/partners': typeof PartnersRoute
  '/projects': typeof ProjectsRoute
  '/returns': typeof ReturnsRoute
  '/rfq': typeof RfqRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/track': typeof TrackRoute
  '/trade': typeof TradeRoute
  '/warranty': typeof WarrantyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bundles/$slug': typeof BundlesSlugRoute
  '/desk/customers': typeof DeskCustomersRoute
  '/desk/inventory': typeof DeskInventoryRoute
  '/desk/orders': typeof DeskOrdersRoute
  '/desk/pricing': typeof DeskPricingRoute
  '/desk/promotions': typeof DeskPromotionsRoute
  '/desk/reports': typeof DeskReportsRoute
  '/desk/reviews': typeof DeskReviewsRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$sku': typeof ProductSkuRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/desk': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accessibility': typeof AccessibilityRoute
  '/account': typeof AccountRoute
  '/blog': typeof BlogRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/collections': typeof CollectionsRoute
  '/contact': typeof ContactRoute
  '/desk': typeof DeskRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/new': typeof NewRoute
  '/partners': typeof PartnersRoute
  '/projects': typeof ProjectsRoute
  '/returns': typeof ReturnsRoute
  '/rfq': typeof RfqRoute
  '/search': typeof SearchRoute
  '/shop': typeof ShopRouteWithChildren
  '/sitemap': typeof SitemapRoute
  '/track': typeof TrackRoute
  '/trade': typeof TradeRoute
  '/warranty': typeof WarrantyRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/bundles/$slug': typeof BundlesSlugRoute
  '/desk/customers': typeof DeskCustomersRoute
  '/desk/inventory': typeof DeskInventoryRoute
  '/desk/orders': typeof DeskOrdersRoute
  '/desk/pricing': typeof DeskPricingRoute
  '/desk/promotions': typeof DeskPromotionsRoute
  '/desk/reports': typeof DeskReportsRoute
  '/desk/reviews': typeof DeskReviewsRoute
  '/legal/$slug': typeof LegalSlugRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/order/$id': typeof OrderIdRoute
  '/product/$sku': typeof ProductSkuRoute
  '/sectors/$slug': typeof SectorsSlugRoute
  '/shop/$slug': typeof ShopSlugRoute
  '/desk/': typeof DeskIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accessibility'
    | '/account'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/desk'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/new'
    | '/partners'
    | '/projects'
    | '/returns'
    | '/rfq'
    | '/search'
    | '/shop'
    | '/sitemap'
    | '/track'
    | '/trade'
    | '/warranty'
    | '/blog/$slug'
    | '/bundles/$slug'
    | '/desk/customers'
    | '/desk/inventory'
    | '/desk/orders'
    | '/desk/pricing'
    | '/desk/promotions'
    | '/desk/reports'
    | '/desk/reviews'
    | '/legal/$slug'
    | '/locations/$slug'
    | '/order/$id'
    | '/product/$sku'
    | '/sectors/$slug'
    | '/shop/$slug'
    | '/desk/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/accessibility'
    | '/account'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/new'
    | '/partners'
    | '/projects'
    | '/returns'
    | '/rfq'
    | '/search'
    | '/shop'
    | '/sitemap'
    | '/track'
    | '/trade'
    | '/warranty'
    | '/blog/$slug'
    | '/bundles/$slug'
    | '/desk/customers'
    | '/desk/inventory'
    | '/desk/orders'
    | '/desk/pricing'
    | '/desk/promotions'
    | '/desk/reports'
    | '/desk/reviews'
    | '/legal/$slug'
    | '/locations/$slug'
    | '/order/$id'
    | '/product/$sku'
    | '/sectors/$slug'
    | '/shop/$slug'
    | '/desk'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/accessibility'
    | '/account'
    | '/blog'
    | '/cart'
    | '/checkout'
    | '/collections'
    | '/contact'
    | '/desk'
    | '/forgot-password'
    | '/help'
    | '/login'
    | '/new'
    | '/partners'
    | '/projects'
    | '/returns'
    | '/rfq'
    | '/search'
    | '/shop'
    | '/sitemap'
    | '/track'
    | '/trade'
    | '/warranty'
    | '/blog/$slug'
    | '/bundles/$slug'
    | '/desk/customers'
    | '/desk/inventory'
    | '/desk/orders'
    | '/desk/pricing'
    | '/desk/promotions'
    | '/desk/reports'
    | '/desk/reviews'
    | '/legal/$slug'
    | '/locations/$slug'
    | '/order/$id'
    | '/product/$sku'
    | '/sectors/$slug'
    | '/shop/$slug'
    | '/desk/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AccountRoute: typeof AccountRoute
  BlogRoute: typeof BlogRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  CollectionsRoute: typeof CollectionsRoute
  ContactRoute: typeof ContactRoute
  DeskRoute: typeof DeskRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  NewRoute: typeof NewRoute
  PartnersRoute: typeof PartnersRoute
  ProjectsRoute: typeof ProjectsRoute
  ReturnsRoute: typeof ReturnsRoute
  RfqRoute: typeof RfqRoute
  SearchRoute: typeof SearchRoute
  ShopRoute: typeof ShopRouteWithChildren
  SitemapRoute: typeof SitemapRoute
  TrackRoute: typeof TrackRoute
  TradeRoute: typeof TradeRoute
  WarrantyRoute: typeof WarrantyRoute
  BundlesSlugRoute: typeof BundlesSlugRoute
  LegalSlugRoute: typeof LegalSlugRoute
  LocationsSlugRoute: typeof LocationsSlugRoute
  OrderIdRoute: typeof OrderIdRoute
  ProductSkuRoute: typeof ProductSkuRoute
  SectorsSlugRoute: typeof SectorsSlugRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collections': {
      id: '/collections'
      path: '/collections'
      fullPath: '/collections'
      preLoaderRoute: typeof CollectionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk': {
      id: '/desk'
      path: '/desk'
      fullPath: '/desk'
      preLoaderRoute: typeof DeskRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/new': {
      id: '/new'
      path: '/new'
      fullPath: '/new'
      preLoaderRoute: typeof NewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners': {
      id: '/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof PartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects': {
      id: '/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfq': {
      id: '/rfq'
      path: '/rfq'
      fullPath: '/rfq'
      preLoaderRoute: typeof RfqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap': {
      id: '/sitemap'
      path: '/sitemap'
      fullPath: '/sitemap'
      preLoaderRoute: typeof SitemapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track': {
      id: '/track'
      path: '/track'
      fullPath: '/track'
      preLoaderRoute: typeof TrackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trade': {
      id: '/trade'
      path: '/trade'
      fullPath: '/trade'
      preLoaderRoute: typeof TradeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/warranty': {
      id: '/warranty'
      path: '/warranty'
      fullPath: '/warranty'
      preLoaderRoute: typeof WarrantyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/bundles/$slug': {
      id: '/bundles/$slug'
      path: '/bundles/$slug'
      fullPath: '/bundles/$slug'
      preLoaderRoute: typeof BundlesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/desk/': {
      id: '/desk/'
      path: '/'
      fullPath: '/desk/'
      preLoaderRoute: typeof DeskIndexRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/customers': {
      id: '/desk/customers'
      path: '/customers'
      fullPath: '/desk/customers'
      preLoaderRoute: typeof DeskCustomersRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/inventory': {
      id: '/desk/inventory'
      path: '/inventory'
      fullPath: '/desk/inventory'
      preLoaderRoute: typeof DeskInventoryRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/orders': {
      id: '/desk/orders'
      path: '/orders'
      fullPath: '/desk/orders'
      preLoaderRoute: typeof DeskOrdersRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/pricing': {
      id: '/desk/pricing'
      path: '/pricing'
      fullPath: '/desk/pricing'
      preLoaderRoute: typeof DeskPricingRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/promotions': {
      id: '/desk/promotions'
      path: '/promotions'
      fullPath: '/desk/promotions'
      preLoaderRoute: typeof DeskPromotionsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/reports': {
      id: '/desk/reports'
      path: '/reports'
      fullPath: '/desk/reports'
      preLoaderRoute: typeof DeskReportsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/desk/reviews': {
      id: '/desk/reviews'
      path: '/reviews'
      fullPath: '/desk/reviews'
      preLoaderRoute: typeof DeskReviewsRouteImport
      parentRoute: typeof DeskRoute
    }
    '/legal/$slug': {
      id: '/legal/$slug'
      path: '/legal/$slug'
      fullPath: '/legal/$slug'
      preLoaderRoute: typeof LegalSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/locations/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/order/$id': {
      id: '/order/$id'
      path: '/order/$id'
      fullPath: '/order/$id'
      preLoaderRoute: typeof OrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$sku': {
      id: '/product/$sku'
      path: '/product/$sku'
      fullPath: '/product/$sku'
      preLoaderRoute: typeof ProductSkuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sectors/$slug': {
      id: '/sectors/$slug'
      path: '/sectors/$slug'
      fullPath: '/sectors/$slug'
      preLoaderRoute: typeof SectorsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop/$slug': {
      id: '/shop/$slug'
      path: '/$slug'
      fullPath: '/shop/$slug'
      preLoaderRoute: typeof ShopSlugRouteImport
      parentRoute: typeof ShopRoute
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface DeskRouteChildren {
  DeskCustomersRoute: typeof DeskCustomersRoute
  DeskInventoryRoute: typeof DeskInventoryRoute
  DeskOrdersRoute: typeof DeskOrdersRoute
  DeskPricingRoute: typeof DeskPricingRoute
  DeskPromotionsRoute: typeof DeskPromotionsRoute
  DeskReportsRoute: typeof DeskReportsRoute
  DeskReviewsRoute: typeof DeskReviewsRoute
  DeskIndexRoute: typeof DeskIndexRoute
}

const DeskRouteChildren: DeskRouteChildren = {
  DeskCustomersRoute: DeskCustomersRoute,
  DeskInventoryRoute: DeskInventoryRoute,
  DeskOrdersRoute: DeskOrdersRoute,
  DeskPricingRoute: DeskPricingRoute,
  DeskPromotionsRoute: DeskPromotionsRoute,
  DeskReportsRoute: DeskReportsRoute,
  DeskReviewsRoute: DeskReviewsRoute,
  DeskIndexRoute: DeskIndexRoute,
}

const DeskRouteWithChildren = DeskRoute._addFileChildren(DeskRouteChildren)

interface ShopRouteChildren {
  ShopSlugRoute: typeof ShopSlugRoute
}

const ShopRouteChildren: ShopRouteChildren = {
  ShopSlugRoute: ShopSlugRoute,
}

const ShopRouteWithChildren = ShopRoute._addFileChildren(ShopRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccessibilityRoute: AccessibilityRoute,
  AccountRoute: AccountRoute,
  BlogRoute: BlogRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  CollectionsRoute: CollectionsRoute,
  ContactRoute: ContactRoute,
  DeskRoute: DeskRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  NewRoute: NewRoute,
  PartnersRoute: PartnersRoute,
  ProjectsRoute: ProjectsRoute,
  ReturnsRoute: ReturnsRoute,
  RfqRoute: RfqRoute,
  SearchRoute: SearchRoute,
  ShopRoute: ShopRouteWithChildren,
  SitemapRoute: SitemapRoute,
  TrackRoute: TrackRoute,
  TradeRoute: TradeRoute,
  WarrantyRoute: WarrantyRoute,
  BundlesSlugRoute: BundlesSlugRoute,
  LegalSlugRoute: LegalSlugRoute,
  LocationsSlugRoute: LocationsSlugRoute,
  OrderIdRoute: OrderIdRoute,
  ProductSkuRoute: ProductSkuRoute,
  SectorsSlugRoute: SectorsSlugRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
